### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#1]
#### Screenshot
![Screenshot 2020-03-14 at 22 13 15](https://user-images.githubusercontent.com/1295800/76690539-39fcd600-6641-11ea-8265-e4c4847420c3.png)

#### Used by
 - All the projects

#### Name
 - Header

#### Children
 - Logo
 - MenuItems
 - ProfileItems (This needs a better name)
#### Other
 - TBD

**Comment by aniri** [comment]
in progress @acis
