### ISSUE TITLE
ListHeader component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#10]
#### Screenshots
![Screenshot 2020-03-15 at 11 19 34](https://user-images.githubusercontent.com/1295800/76700057-b7f9c500-66b3-11ea-8ea7-ef984a733343.png)

![Screenshot 2020-03-15 at 15 54 53](https://user-images.githubusercontent.com/1295800/76703904-914c8600-66d5-11ea-8512-018ec2b4fe25.png)

#### Used by
 - Ce Ma Fac
 - Stam Acasa
 - Diaspora Hub

#### Name
 - ListHeader (I think we could find a better name for this)

#### Props `ListHeader`
 - title (`string`)

#### Other
 - TBD

**Comment by ionmosincat** [comment]
@moonflare: Pot sa il iau pe asta?

**Comment by moonflare** [comment]
@ionmosincat Poate sa se extinda si pe 2 randuri
![Screenshot 2020-03-15 at 15 54 53](https://user-images.githubusercontent.com/1295800/76703901-872a8780-66d5-11ea-81df-7e28a5ccf234.png)
