### ISSUE TITLE
Create decision tree form that collects answers

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/taskforce-fe-components#106]
As part of the Stam Acasa project, we need to create an assessment for similar to the decision tree on Ce ma fac project.

The contents of the navigable decision tree can be found here, and are provided through an API call: https://github.com/code4romania/stam-acasa/blob/data/json-q1/jsondata/schema.json

The decision tree UX can be found here: 
https://www.figma.com/file/rdg8gZtSWNYaVtupMtdhST/CoVid---Stam-Acasa?node-id=39%3A138
![Completeaza formular de evaluare](https://user-images.githubusercontent.com/15039873/77786715-f05fb280-7066-11ea-8511-58b321c50326.png)

After an user completes an assessment, the responses need to be sent back to the API, to an endpoint that can be configurable.
The responses will contain the following information:
- schema version
- a dictionary of key - question - value (key = question id, question = question text, value = answer)

**Comment by mmircea16** [comment]
Vreau sa ma apuc de acest issue
