### ISSUE TITLE
Add new type of list item component

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#107]
Add one more listitem version, check out https://taskforce-fe-components.now.sh/?path=/story/listitem--with-inactive-state as an example.

![Group 475](https://user-images.githubusercontent.com/15039873/77817576-9269b400-70d4-11ea-8d37-1b69c55d1e3d.png)

-----

#### Used by
- Stam acasa
- Diaspora hub
- Ce trebuie sa fac
- Whos Who

#### Names
 - SearchResultListItem

#### Props SearchResultListItem
- date (`date`) - optional
- title (`string`)
- shortText (`string`) - optional
- readMoreText (`string`)
- readMoreLink (`string`)

**Comment by Utwo** [comment]
:raised_hand_with_fingers_splayed:

**Comment by aniri** [comment]
It should also support displaying this kind of content

![list](https://user-images.githubusercontent.com/1358055/77819044-8257d180-70e0-11ea-8003-cf5fd37af15d.png)
