### ISSUE TITLE
Update accordion component layout

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#108]
Current version https://taskforce-fe-components.now.sh/?path=/story/accordion--default

Please update design to:
![accordion_closed](https://user-images.githubusercontent.com/1358055/77818351-55082500-70da-11ea-8b19-4cd53f43aae1.png)

Wireframe: https://www.figma.com/file/xdKbESSX397obRR5m9DMM5/CoVid---who-is-who?node-id=0%3A1

Also, accordion content should be able to support html in the content with images and links.

**Comment by alininayeh** [comment]
I can take this one.
