### ISSUE TITLE
SocialsShare component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#11]
#### Screenshots
![Screenshot 2020-03-15 at 11 59 37](https://user-images.githubusercontent.com/1295800/76700136-c4325200-66b4-11ea-92f3-1d492607b665.png)

#### Used by
 - Ce Ma Fac
 - Stam Acasa
 - Diaspora Hub

#### Name
 - SocialsShare (I think we could find a better name for this)

#### Props `SocialsShare`
- currentPage (`string`)

#### Other
 - Is the only prop the current page that we want to share?

**Comment by adascaliteiradu** [comment]
As far as I know, Instagram does not allow sharing pages via API. Can anybody confirm this information, please?

https://warfareplugins.com/support/instagram-sharing-button/

**Comment by adascaliteiradu** [comment]
As vrea sa il iau eu pe acesta.
