### ISSUE TITLE
Social icons buttons are not center aligned with "Share on" text

### ISSUE THREAD

**Issue by zauan** [code4romania/taskforce-fe-components#111]
In design arata asa 
![CoVid - Ce Ma Fac – Figma 2020-03-28 11 42 41 (1)](https://user-images.githubusercontent.com/5928748/77820256-9bb14b80-70e9-11ea-8454-ac88ec77e355.png)

iar implementarea arata asa 
![Ce trebuie să fac 2020-03-28 11 45 47 (1)](https://user-images.githubusercontent.com/5928748/77820267-b4216600-70e9-11ea-8a73-ce7877652d72.png)

**Comment by moonflare** [comment]
Issue in progress, @pdamoc
