### ISSUE TITLE
Allow the customization of the DevelopedBy component

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/taskforce-fe-components#113]
The [`DevelopedBy` component](https://github.com/code4romania/taskforce-fe-components/tree/master/src/components/developed-by) should allow displaying fewer stakeholders if the case arises.
It should be able to receive arguments on whether it should display specific logos and text

Customizations which should be included:
- [ ] with or without the Government & ADR
- [ ] with or without the DSU line

The default state (without any parameters) should be **with** the government displayed but **without** the DSU line
The Code4ro logo should always be displayed

**Comment by mihaela94** [comment]
Hello, as vrea sa iau eu taskul acesta.

**Comment by moonflare** [comment]
> with or without the DSU line

Hey @mihaela94 @tudoramariei 👋 At the moment we have a flag for the `DSU` line. It's called `showSecondLine`. We could add a new flag for this something like `showDSU` but at the same time keep the old one for backwards compatibility
