### ISSUE TITLE
Typo somewhere in the DevelopedBy component

### ISSUE THREAD

**Issue by CristiHabliuc** [code4romania/taskforce-fe-components#127]
When using `DevelopedBy`, it works fine, but I see this error in the console:

![Screenshot 2020-03-28 at 18 34 08](https://user-images.githubusercontent.com/1491833/77828232-e1d6d100-7122-11ea-9f5f-20269484360b.png)

**Comment by aniri** [comment]
@CristiHabliuc in what version? :thinking:

**Comment by CristiHabliuc** [comment]
Happens in 1.0.4 too

**Comment by moonflare** [comment]
Hmm. It's been fixed in [v1.0.1](https://github.com/code4romania/taskforce-fe-components/releases/tag/v1.0.1). Perhaps you have an older version in `node_modules`?

**Comment by moonflare** [comment]
I checked all the version `v1.0.1+` and all good. Will close this issue.
