### ISSUE TITLE
Enhance decision tree with multiple choice

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/taskforce-fe-components#136]
There are situations where questions on a form require a multiple choice.
We need to enhance the `Form` component to support multiple choice, but we will support this feature without any changes to the navigation. So, in multiple choice questions we will not override the default navigation with navigation from options.

**Comment by mmircea16** [comment]
I will pick this up - can't assign it to myself though...

**Comment by surdu** [comment]
@mmircea16 was this closed in #138 ?

**Comment by surdu** [comment]
Closed in #138
