### ISSUE TITLE
Implement county/city component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/taskforce-fe-components#147]
As part of the Stam Acasa project, we realized we need to develop 2 components for inserting information about County/City in Romania.

<img width="489" alt="Screenshot 2020-04-09 at 12 17 33" src="https://user-images.githubusercontent.com/15039873/78879119-2421db80-7a5c-11ea-931e-f077eed5004a.png">

The components should use JSON files for configuration.
The components should be able to return the data entered by an user.
The components are dropdown or searchable - if I use the dropdown function I can see all the elements, if I start typing the component does a search through the possible values. The city component depends on the county one, we should not be able to interact with the city component until the county one is filled in with a value.

**Comment by dragosrobertn** [comment]
As agreed I will be taking this, but I will be updating the current existing component https://taskforce-fe-components.now.sh/?path=/story/filter-modal--usage.

**Comment by RaduCStefanescu** [comment]
@dragosrobertn do you have any updates on this one?
We will need to integrate it to Stam Acasa project pretty soon.
Thank you!

**Comment by dragosrobertn** [comment]
Should be done today.

**Comment by dragosrobertn** [comment]
Myself and @Tanu1994 paired on this one.
