### ISSUE TITLE
Extend DATE_PICKER on Form component to DATE_TIME_PICKER

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/taskforce-fe-components#158]
We need to extend the DATE_PICKER option on Form component to handle datetime values as well. In Stăm Acasă project, we require an option on the form where a user inserts date and time values. Currently, we only have a DATE_PICKER component, that displays a calendar. We need to extend this option, to be able to choose a time as well.

**Comment by aniri** [comment]
closing this as it was fixed in #161
