### ISSUE TITLE
SearchInput component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#16]
#### Screenshots
![Screenshot 2020-03-15 at 16 29 48](https://user-images.githubusercontent.com/1295800/76704596-5862e000-66da-11ea-8b8d-02daf11f55b5.png)

#### Used by
 - Ce Ma Fac
 - Stam Acasa
 - Diaspora Hub

#### Name
 - SearchInput (I think we could find a better name for this)

#### Props `SearchInput`
 - hasIcon (`bool`)
 - value (`string`)
 - placeholder (`string`)
 - onValueChange (`function`)

#### Other
 - TBD

**Comment by adascaliteiradu** [comment]
Can I?
