### ISSUE TITLE
Unused CSS

### ISSUE THREAD

**Issue by Utwo** [code4romania/taskforce-fe-components#184]
After #180 is done, the next big concern is high CSS bundle size with a lot of unused code.

Now, we import bulma in fe-components but we only use a very small subset of bulma features. For decreasing the size of the bundle we can remove bulma altogether and write our own CSS.
In order for us not to end up in the same situation after a couple of month with a lot of unused CSS, I will propose to use a CSS-in-JS solution. 

Note that because we remove bulma, this will be a breaking change. Consumer app should import Bulma with whatever features it needs.

**Comment by surdu** [comment]
Personally, I have CSS-in-JS ... 

How about [importing only what we need](https://bulma.io/documentation/customize/with-sass-cli/#6-add-your-own-bulma-styles) form Bulma

**Comment by surdu** [comment]
Scratch that... We already do this: https://github.com/code4romania/taskforce-fe-components/blob/master/src/styles.scss

We seem to import only what we need. There might be one - two modules that might not be needed anymore, but we don't import the whole Bulma library.

**Comment by Utwo** [comment]
Yes, it's fine, we can close this :+1:
