### ISSUE TITLE
Create incubated-by component with one or more partners logos

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/taskforce-fe-components#189]
Currently, the [incubated-by](https://taskforce-fe-components.now.sh/?path=/story/incubated-by--normal) logo only allows for the display of the `Code4Romania Taskforce` logo.

Another version of this component should be implemented to allow the display of partner logos, as in the image below
![image](https://user-images.githubusercontent.com/2820084/81535891-449ec780-9373-11ea-8ec1-10b6d1a4f307.png)

Currently, displaying only one partner logo is necessary, though we may have multiple partners in the future. So it would be useful if the component would allow for more than one partner logo. This is up for discussions.

**Comment by cipick** [comment]
Can do it if that's fine 😁

**Comment by tudoramariei** [comment]
That'd be great, @cipick! It's all yours 😄
