### ISSUE TITLE
DevelopedBy component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#2]
#### Screenshot
![Screenshot 2020-03-15 at 19 18 03](https://user-images.githubusercontent.com/1295800/76707712-e1d1dc80-66f1-11ea-8d46-b40ef9746c66.png)

#### Used by
 - All the projects

#### Name
 - DevelopedBy (Maybe we can find a better name)

#### Children
 - DeveloperLogo
 - PartnerLogo

#### Other
 - Should the text for both logos be there by default?
 - Should we allow people to override it?

**Comment by victorbojica** [comment]
Iau eu issueul asta

**Comment by victorbojica** [comment]
Intrebare. Componentele  children, exista deja pe undeva sau trebuie create si ele ? (intrebare valabila si pentru restul issue-urilor). Am inteles ca mai exista deja ceva lucrat.

**Comment by moonflare** [comment]
@victorbojica Nu exista deja. Trebuiesc create si ele. Practic, vrem un mod prin care sa avem imaginile alea doua dinamice.

**Comment by CristiHabliuc** [comment]
S-a schimbat si logo-ul guvernului iar:

![logo-gov](https://user-images.githubusercontent.com/1491833/76841089-f5d82400-6840-11ea-90b9-36680891caa8.png)

**Comment by moonflare** [comment]
Thanks @CristiHabliuc! Left a comment already to the #33 PR 🙌
