### ISSUE TITLE
Login form inputs

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#29]
#### Screenshots
![login](https://user-images.githubusercontent.com/1358055/76792183-28dfd080-67cb-11ea-90f3-e0df30a787c0.JPG)

#### Wireframes
https://www.figma.com/file/ntWPKzNTSoml4tQS75z9SP/CoVid---Diaspora-Hub?node-id=0%3A1

-----

#### Used by
- Stam acasa
- Diaspora hub

#### Names
 - Input

#### Props
 - label (`string`)
 - type (`enum` `{ text | password}`)

**Comment by robiXxu** [comment]
I'll take this if that's ok. :)
