### ISSUE TITLE
Hero component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#3]
#### Screenshot
![Screenshot 2020-03-14 at 22 26 57](https://user-images.githubusercontent.com/1295800/76690711-3cf8c600-6643-11ea-874f-b26e877f51db.png)
--------
![Screenshot 2020-03-14 at 22 33 25](https://user-images.githubusercontent.com/1295800/76690786-1c7d3b80-6644-11ea-933f-f39eaa8f71e7.png)
------

#### Used by
 - All the projects

#### Name
 - Hero

#### Children
 - Icon (optional)

#### Props
 - Title (required)
 - Subtitle (optional)

#### Other
 - We can can have Only title, title and subtite, title and icon, and all of them at the same time.

**Comment by acis** [comment]
@moonflare ✋ il iau eu pe asta
