### ISSUE TITLE
Form inputs

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#30]
#### Screenshots
![form1](https://user-images.githubusercontent.com/1358055/76792358-91c74880-67cb-11ea-955f-0ea08d788b17.JPG)
![forms2](https://user-images.githubusercontent.com/1358055/76792365-9429a280-67cb-11ea-8dbc-6557d02cc23d.JPG)

#### Wireframes
https://www.figma.com/file/ntWPKzNTSoml4tQS75z9SP/CoVid---Diaspora-Hub?node-id=0%3A1

-----

#### Used by
- Stam acasa
- Diaspora hub

#### Props
- varsta (`dropdown`, `pre-configured`)
- sex (`dropdown`, `pre-configured`)
- country (`dropdown`, `pre-configured`)
- city (`string`)
- pre-existing conditions (`dropdown`, `pre-configured`)

**Comment by danut0nline** [comment]
Pot sa iau eu incidentul asta
