### ISSUE TITLE
Tabbed list

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#31]
#### Screenshots
![tabs1](https://user-images.githubusercontent.com/1358055/76792569-fc788400-67cb-11ea-9bc8-daaaefdb7a64.JPG)
![tabs2](https://user-images.githubusercontent.com/1358055/76792571-fda9b100-67cb-11ea-8a07-156db0d202e6.JPG)

#### Wireframes
https://www.figma.com/file/ntWPKzNTSoml4tQS75z9SP/CoVid---Diaspora-Hub?node-id=0%3A1

-----

#### Used by
- Stam acasa
- Diaspora hub

#### Names
 - TabbedList
 - TabbedListItem

#### Props TabbedListItem
- color (`string`)
- date (`date`)
- resultText (`string`)
- simptomText (`string`)
- onClick (`function`)

**Comment by acis** [comment]
🙋🏼‍♀️

**Comment by surdu** [comment]
@acis Any updates on this?
