### ISSUE TITLE
Update header/footer components to use the grid system

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#47]
#### Description
Currently, both the `Header` and the `Footer` components should be using the grid system. Their contents should be wrapped with the [container](https://bulma.io/documentation/layout/container/) CSS class from Bulma. Please note that, for example the background color for the footer needs to be full width. Please check https://stirioficiale.ro for reference.

#### Example
![Screenshot 2020-03-18 at 20 00 10](https://user-images.githubusercontent.com/1295800/76997313-696a5600-6953-11ea-9c12-e6307f0ac891.png)

**Comment by oanamun** [comment]
I can take this
