### ISSUE TITLE
Instruments components

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#5]
#### Screenshots
![Screenshot 2020-03-14 at 22 52 53](https://user-images.githubusercontent.com/1295800/76691046-c52c9a80-6646-11ea-95eb-e045c02ae1c7.png)
------
![Screenshot 2020-03-14 at 22 51 41](https://user-images.githubusercontent.com/1295800/76691047-c5c53100-6646-11ea-9329-f91aaaac620c.png)
----

#### Used by
 - Ce Ma Fac
 - Stam Acasa
 - Diaspora Hub

#### Names
 - Instruments
 - InstrumentsItem

#### Props `Instruments`
 - layout (for the 2 different types, maybe a better name needed)

#### Props `InstrumentsItem`
 - color (`string`)
 - title (`string`)
 - content (`string`)
 - cta (`Button`) // Allow class prop to the btn component

#### Other
 - For the title and the icon, we could probably use a separate component

**Comment by boicualexandru** [comment]
Pot sa il iau eu?

**Comment by moonflare** [comment]
Salut @boicualexandru, Titlul cu iconul respectiv poti sa le omiti, cel mai probabil o sa fi folosit cu o alta componenta.

**Comment by boicualexandru** [comment]
And question. Componenta **Instruments** este un container pentru InstrumentsItem si InstrumentsSearch? 
Iar layout prop se refera la one or multiple columns, right?

**Comment by aniri** [comment]
@moonflare I think we can extract the search as a separate component :) what do you think?

**Comment by aniri** [comment]
and @boicualexandru similar components were implemented in the https://github.com/code4romania/ce-ma-fac project. we are moving to this repo to have reusable components. you might want to check what was already implemented and see if you can reuse/extract here some of the work :D

**Comment by moonflare** [comment]
I extracted the search input field and created another issue for that #16

**Comment by boicualexandru** [comment]
@aniri
> and @boicualexandru similar components were implemented in the https://github.com/code4romania/ce-ma-fac project. we are moving to this repo to have reusable components. you might want to check what was already implemented and see if you can reuse/extract here some of the work :D

I seems that I don't have access to that repo.
