### ISSUE TITLE
Newsletter input component

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#52]
#### Wireframes
https://www.figma.com/file/yVO3Meu9PwRPhWI1JBtwKd/newsletter?node-id=0%3A1

-----

#### Used by
- All projects

#### Props
- mailchimpId

**Comment by andreicioban** [comment]
Je suis. But after 19:00.
If anyone is available to start sooner i don't mind.

**Comment by andreicioban** [comment]
On it.
