### ISSUE TITLE
DevelopedBy and IncubatedBy components need to support links

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#55]
Currently, we can't interact with the DevelopedBy and IncubatedBy components. We need to have support links for them

**Comment by acis** [comment]
@moonflare  also, the incubatedBy CSS needs a small change, could you add this pls
`.incubated-by { 
...

padding: 0 1.25rem;
}`

**Comment by moonflare** [comment]
> @moonflare also, the incubatedBy CSS needs a small change, could you add this pls
> 
> ```css
> .incubated-by { 
>     ...
>     padding: 0 1.25rem;
> }
> ```

Is this for the smaller screens?

**Comment by moonflare** [comment]
> > @moonflare also, the incubatedBy CSS needs a small change, could you add this pls
> > ```css
> > .incubated-by { 
> >     ...
> >     padding: 0 1.25rem;
> > }
> > ```
> 
> Is this for the smaller screens?

Ah, I see. It's because of the `.footer-content` having it. I would rather remove it from the footer than add it to this component. Also, the `useful tools` cards have some weird margins because of `.column`. We could probably remove that as well to align with the rest.
