### ISSUE TITLE
Enhance developed by component - add also version with two lines

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#58]
Add a new developed by option besides this one https://taskforce-fe-components.now.sh/?path=/story/developed-by--normal 

It should have two lines, please see: https://www.figma.com/file/AAFjYsqFI834AAcLmAWm0O/Headers?node-id=0%3A1

**Comment by acis** [comment]
🙋

**Comment by andreiio** [comment]
Am făcut update în figma, scos logoul Ministerului Sănătății.
