### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#6]
#### Screenshots
![Screenshot 2020-03-14 at 23 15 38](https://user-images.githubusercontent.com/1295800/76691339-30c43700-664a-11ea-948a-1682ddb0c831.png)

-----

#### Used by
 - All the apps

#### Names
 - Footer

#### Children
 - Links

**Comment by ionmosincat** [comment]
L-as lua eu pe asta

**Comment by moonflare** [comment]
@ionmosincat Issues care sunt marcate ca `high priority` sunt ale care nu sunt implementate. Asta spre exemplu e implementat in diferite proiecte deja, si e low priority. O sa le mutam pe cele implementate in repo-ul asta, la final.

**Comment by ionmosincat** [comment]
@moonflare: Ok, am inteles, iau altul.

**Comment by DanielStoica85** [comment]
Can I grab this one?
