### ISSUE TITLE
IncubatedBy component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#7]
#### Screenshots
![Screenshot 2020-03-14 at 23 15 10](https://user-images.githubusercontent.com/1295800/76691373-7ed93a80-664a-11ea-88cf-26adb45bdc34.png)

-----

#### Used by
 - All the apps

#### Names
 - IncubatedBy

#### Children
 - Logo

**Comment by victorbojica** [comment]
Iau eu issueul asta
