### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by moonflare** [code4romania/taskforce-fe-components#8]
#### Screenshots
![Screenshot 2020-03-14 at 23 17 27](https://user-images.githubusercontent.com/1295800/76691411-c5c73000-664a-11ea-9e59-030dbb8b2900.png)
![Screenshot 2020-03-14 at 23 17 23](https://user-images.githubusercontent.com/1295800/76691412-c65fc680-664a-11ea-943a-eb4f8edd924c.png)

-----

#### Used by
 - All the apps

#### Names
 - Button

#### Props
 - label (`string`)
 - onClick (`function`)
 - type (`enum` `{ primary | secondary }`)

#### Other
 - We also have buttons for login form, should we have the same component for those as well?

**Comment by surdu** [comment]
@moonflare Il iau eu pe asta, daca e ok
