### ISSUE TITLE
Create sidebar menu

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/taskforce-fe-components#82]
Some of the content we need to display in our webpages becomes a wall of text, so in order to make the content more readable, we also need to implement a component for separating pages into sub-pages

The side bar menu has the text separated in pages and subpages, and it eases the navigation through the content
https://www.figma.com/proto/XDcxBzr6MdMlrZmmlBTYvu/Content-design---CeMaFac?node-id=1%3A214&scaling=min-zoom

**Comment by oanamun** [comment]
I can take this
