### ISSUE TITLE
Hero component title is now centered

### ISSUE THREAD

**Issue by surdu** [code4romania/taskforce-fe-components#86]
**Expected**
<img width="892" alt="Screenshot 2020-03-22 at 14 43 18" src="https://user-images.githubusercontent.com/11520795/77249673-86e93980-6c4b-11ea-9157-440b3fbffdd0.png">

**In Storybook**
<img width="981" alt="Screenshot 2020-03-22 at 14 42 48" src="https://user-images.githubusercontent.com/11520795/77249677-9072a180-6c4b-11ea-881c-52c067e5fddb.png">

**Comment by moonflare** [comment]
Fixed in https://github.com/code4romania/taskforce-fe-components/pull/83
