### ISSUE TITLE
Enhance header display on mobile devices - hamburger menu

### ISSUE THREAD

**Issue by aniri** [code4romania/taskforce-fe-components#96]
Current header behavior on mobile:
![Screenshot_20200323-174215_Chrome](https://user-images.githubusercontent.com/1358055/77334774-ed468880-6d2d-11ea-989d-5e9c7071ed61.jpg)

Should be changed to:
![Screenshot_20200323-174224_Chrome](https://user-images.githubusercontent.com/1358055/77334791-f20b3c80-6d2d-11ea-83e6-096ed126a3a8.jpg)

**Comment by dmfarcas** [comment]
I'll work on this

**Comment by dmfarcas** [comment]
The banner issue is also solved in the scope of this ticket
