### ISSUE TITLE
Checkbox checked - no visible change

### ISSUE THREAD

**Issue by milovanderlinden** [code4romania/taskforce-fe-components#97]
When you check the checkbox, the box is not "ticked". I am on firefox, perhaps this is the issue.

**Comment by Utwo** [comment]
Thank you! This happens both on ff and chrome.

**Comment by paul-ghiran** [comment]
Gonna look into this, thank you for pointing it out!

**Comment by bvizureanu** [comment]
@milovanderlinden !!! thank you!
